version: '2'
services:
   learning-agreement-bdd:
     image: postgres
     expose:
       - 5432
     ports:
       - 5432:5432
     volumes:
       - ./localdata/postgres:/var/lib/postgresql/data
     environment:
       - POSTGRES_PASSWORD=root
   learning-agreement-api:
     build: ./learning-agreement-api
     environment:
       - datasourceUrl=jdbc:postgresql://learning-agreement-BDD:5432/
       - datasourceUsername=postgres
       - datasourcePassword=root
     ports:
       - 8080:8080
     depends_on:
       - learning-agreement-bdd
