version: '2'
services:
   learning-agreement-BDD:
     image: postgres
     expose:
       - 5432
     ports:
       - 5432:5432
     volumes:
       - ./localdata/postgres:/var/lib/postgresql/data
     environment:
       - POSTGRES_PASSWORD=<passwordpostgres>
   learning-agreement-API:
     image: 136615499317.dkr.ecr.eu-west-1.amazonaws.com/epack-back:latest
     environment:
       - datasourceUrl=jdbc:postgresql://epack-bdd:5432/
       - datasourceUsername=postgres
       - datasourcePassword=<passwordpostgres>
     ports:
       - 4300:4300
     depends_on:
       - epack-bdd
   learning-agreement-FRONT:
     image: 136615499317.dkr.ecr.eu-west-1.amazonaws.com/epack-front:latest
     environment:
       - backUrl=http:\/\/learning-agreement-API:4300
     ports:
       - 80:4200
     depends_on:
       - learning-agreement-API
